import type { Product, Subcategory } from "./types";

/**
 * Catalogue démo — 24 produits (H33), remplacé par l'API réelle en Phase 6 (H37).
 * Marques et produits fictifs ; visuels = placeholders DA (H32).
 */

export const subcategories: Subcategory[] = [
  { slug: "colliers-harnais", label: "Colliers & Harnais", animal: "chien", description: "Cuir pleine fleur, sangles techniques : chaque collier est testé sur le terrain par notre équipe." },
  { slug: "laisses", label: "Laisses", animal: "chien", description: "Des laisses équilibrées en main, assorties à nos colliers, pensées pour durer des années." },
  { slug: "couchages-paniers", label: "Couchages & Paniers", animal: "chien", description: "Des couchages fermes et déhoussables, dessinés pour s'intégrer au salon." },
  { slug: "jouets", label: "Jouets", animal: "chien", description: "Des jouets robustes en matières naturelles, choisis pour stimuler sans s'effriter." },
  { slug: "gamelles-repas", label: "Gamelles & Repas", animal: "chien", description: "Céramique et inox stables, hauteurs étudiées pour le confort du repas." },
  { slug: "transport-voyage", label: "Transport & Voyage", animal: "chien", description: "Voyager ensemble, sans compromis sur la sécurité ni sur l'allure." },
  { slug: "toilettage-soin", label: "Toilettage & Soin", animal: "chien", description: "Brosses et soins doux, sélectionnés avec des toiletteurs professionnels." },
  { slug: "manteaux-textile", label: "Manteaux & Textile", animal: "chien", description: "Laine et toile cirée, coupes ajustées : l'élégance qui protège vraiment." },
  { slug: "colliers", label: "Colliers", animal: "chat", description: "Colliers légers à détache de sécurité, pensés pour être oubliés par votre chat." },
  { slug: "couchages-cocons", label: "Couchages & Cocons", animal: "chat", description: "Cocons enveloppants en laine et feutre, adoptés dès la première sieste." },
  { slug: "arbres-a-chat-griffoirs", label: "Arbres à chat & Griffoirs", animal: "chat", description: "Bois massif et sisal serré : des griffoirs stables qui embellissent la pièce." },
  { slug: "jouets", label: "Jouets", animal: "chat", description: "Plumes, liège et herbe à chat : des jouets simples qui réveillent l'instinct." },
  { slug: "gamelles-fontaines", label: "Gamelles & Fontaines", animal: "chat", description: "Gamelles basses anti-moustaches et fontaines silencieuses." },
  { slug: "litiere-maison", label: "Litière & Maison", animal: "chat", description: "Maisons de toilette discrètes qui se fondent dans l'intérieur." },
  { slug: "transport-voyage", label: "Transport & Voyage", animal: "chat", description: "Sacs et caisses rassurants, validés vétérinaire pour les trajets sereins." },
  { slug: "habitat-couchage", label: "Habitat & Couchage", animal: "nac", description: "Habitats spacieux en bois non traité, faciles à nettoyer." },
  { slug: "jeux-activite", label: "Jeux & Activité", animal: "nac", description: "Tunnels, ponts et jouets à ronger pour des journées bien remplies." },
  { slug: "repas-accessoires", label: "Repas & Accessoires", animal: "nac", description: "Râteliers et gamelles stables adaptés aux petits museaux." },
];

const cuirCaramel = { name: "Cuir caramel", hex: "#C08A4F" };
const noirBrou = { name: "Brou de noix", hex: "#4A443D" };
const vertSauge = { name: "Vert sauge", hex: "#7F9877" };
const terracotta = { name: "Terracotta", hex: "#C67B54" };
const creme = { name: "Crème", hex: "#EDE8E0" };
const grege = { name: "Grège", hex: "#C9BFAC" };

export const products: Product[] = [
  // ——— Chien · Colliers & Harnais (6) ———
  {
    slug: "collier-cuir-ambre",
    name: "Collier Ambre en cuir pleine fleur",
    brand: "Atelier Fauve",
    animal: "chien",
    subcategory: "colliers-harnais",
    price: 5900,
    shortDescription: "Un collier en cuir de tannage végétal qui se patine avec les années. Coutures sellier, boucle laiton massif.",
    curatorNote: "Nous avons visité l'atelier à Graulhet : le cuir vient d'une tannerie française certifiée, et la boucle est garantie à vie. C'est le collier que porte le chien de notre fondatrice.",
    material: "Cuir",
    details: [
      { title: "Description complète", content: "Cuir pleine fleur de tannage végétal, teinté dans la masse. Chaque collier est coupé, cousu et bordé à la main. La patine se développe avec le temps et l'usage." },
      { title: "Matières & entretien", content: "Cuir français, boucle laiton massif. Nourrir avec un baume incolore deux fois par an. Éviter l'immersion prolongée." },
      { title: "Dimensions & tailles", content: "S : tour de cou 28–34 cm · M : 34–42 cm · L : 42–52 cm. Largeur 25 mm." },
      { title: "Fabrication & origine", content: "Fabriqué à Graulhet (Tarn, France) par un atelier familial fondé en 1962." },
    ],
    colors: [cuirCaramel, noirBrou],
    sizes: [
      { name: "S", stock: 8 },
      { name: "M", stock: 12 },
      { name: "L", stock: 0 },
    ],
    gabarits: ["S", "M", "L"],
    isNew: false,
    curatedRank: 1,
    reviews: [
      { author: "Camille R.", rating: 5, title: "Magnifique et solide", text: "La qualité du cuir est bluffante, il s'assouplit vite sans se déformer. Après six mois d'usage quotidien, il est encore plus beau qu'au premier jour.", context: "Berger australien, 24 kg — taille L", date: "2026-05-12", verified: true },
      { author: "Julien M.", rating: 5, title: "Le premier collier qui dure", text: "Troisième collier en deux ans pour mon staffie… celui-ci tient enfin. La boucle est massive et rassurante.", context: "Staffordshire, 18 kg — taille M", date: "2026-04-02", verified: true },
      { author: "Anne L.", rating: 4, title: "Très beau, taille juste", text: "Splendide, mais prenez la taille au-dessus si votre chien est entre deux mesures.", context: "Cocker, 13 kg — taille M", date: "2026-03-18", verified: true },
    ],
    pairsWith: ["laisse-cuir-ambre", "medaille-laiton"],
    tone: "caramel",
  },
  {
    slug: "harnais-randonnee-sequoia",
    name: "Harnais de randonnée Séquoia",
    brand: "Terre & Truffe",
    animal: "chien",
    subcategory: "colliers-harnais",
    price: 7400,
    shortDescription: "Un harnais en Y qui laisse l'épaule libre, avec poignée dorsale et sangles rembourrées. Pensé pour les kilomètres.",
    curatorNote: "Testé sur 300 km de sentiers par deux membres de l'équipe. Aucun point de frottement constaté, même mouillé — c'est rare.",
    material: "Textile technique",
    details: [
      { title: "Description complète", content: "Coupe en Y anatomique, trois points de réglage, poignée dorsale renforcée et anneau avant anti-traction. Bandes réfléchissantes discrètes." },
      { title: "Matières & entretien", content: "Toile ripstop recyclée, rembourrage maille 3D. Lavable en machine à 30 °C, séchage à l'air libre." },
      { title: "Dimensions & tailles", content: "S : poitrail 45–60 cm · M : 60–75 cm · L : 75–95 cm." },
      { title: "Fabrication & origine", content: "Dessiné en France, fabriqué au Portugal dans un atelier audité." },
    ],
    colors: [vertSauge, noirBrou, terracotta],
    sizes: [
      { name: "S", stock: 5 },
      { name: "M", stock: 9 },
      { name: "L", stock: 4 },
    ],
    gabarits: ["S", "M", "L", "XL"],
    isNew: true,
    curatedRank: 2,
    reviews: [
      { author: "Thomas B.", rating: 5, title: "Parfait en rando", text: "La poignée dorsale change tout sur les passages rocheux. Séchage très rapide.", context: "Border collie, 19 kg — taille M", date: "2026-06-20", verified: true },
    ],
    pairsWith: ["laisse-trail-amarre", "manteau-pluie-brume"],
    tone: "sage",
  },
  {
    slug: "collier-tresse-olive",
    name: "Collier tressé Olive",
    brand: "Maison Bergame",
    animal: "chien",
    subcategory: "colliers-harnais",
    price: 4200,
    shortDescription: "Corde marine tressée main et cuir au point d'attache : léger, souple, très résistant.",
    curatorNote: "La corde vient d'une corderie bretonne qui équipe des voiliers de course. Nous l'avons choisi pour les chiens qui n'aiment pas le cuir rigide.",
    material: "Corde & cuir",
    details: [
      { title: "Description complète", content: "Tressage serré huit brins, épissures main, renfort cuir au niveau de la boucle. Très léger au porté." },
      { title: "Matières & entretien", content: "Corde polyester marine, cuir tanné végétal. Rinçage à l'eau claire après la mer." },
      { title: "Dimensions & tailles", content: "S : 30–36 cm · M : 36–44 cm · L : 44–54 cm. Diamètre 10 mm." },
    ],
    colors: [vertSauge, terracotta, creme],
    sizes: [
      { name: "S", stock: 11 },
      { name: "M", stock: 7 },
      { name: "L", stock: 6 },
    ],
    gabarits: ["S", "M", "L"],
    isNew: false,
    curatedRank: 8,
    reviews: [
      { author: "Sophie D.", rating: 5, title: "Léger et chic", text: "Ma chienne oublie qu'elle le porte. Les couleurs sont encore plus belles en vrai.", context: "Braque, 22 kg — taille L", date: "2026-02-25", verified: true },
    ],
    pairsWith: ["laisse-tressee-olive"],
    tone: "sage",
  },
  {
    slug: "harnais-ville-faubourg",
    name: "Harnais de ville Faubourg",
    brand: "Atelier Fauve",
    animal: "chien",
    subcategory: "colliers-harnais",
    price: 8900,
    shortDescription: "Cuir souple doublé lainage, boucleries laiton : le harnais habillé des trajets urbains.",
    curatorNote: "Le seul harnais cuir que nous ayons validé : la doublure lainage évite l'échauffement, défaut classique du cuir en harnais.",
    material: "Cuir",
    details: [
      { title: "Description complète", content: "Coupe en H, cuir souple doublé de lainage naturel, quatre réglages. Bouclerie laiton vieilli." },
      { title: "Matières & entretien", content: "Cuir vachette, lainage 100 % laine. Brosser la doublure, nourrir le cuir deux fois par an." },
      { title: "Dimensions & tailles", content: "XS : poitrail 35–45 cm · S : 45–58 cm · M : 58–72 cm." },
    ],
    colors: [cuirCaramel, noirBrou],
    sizes: [
      { name: "XS", stock: 4 },
      { name: "S", stock: 6 },
      { name: "M", stock: 3 },
    ],
    gabarits: ["XS", "S", "M"],
    isNew: false,
    curatedRank: 9,
    reviews: [],
    pairsWith: ["laisse-cuir-ambre"],
    tone: "caramel",
  },
  {
    slug: "collier-puppy-brindille",
    name: "Collier premier âge Brindille",
    brand: "Petit Clan",
    animal: "chien",
    subcategory: "colliers-harnais",
    price: 2900,
    shortDescription: "Ultra-léger et réglable finement pour accompagner la croissance du chiot sans le gêner.",
    curatorNote: "Recommandé par l'éducatrice canine qui relit nos guides : sa légèreté facilite l'habituation au collier dès 8 semaines.",
    material: "Textile technique",
    details: [
      { title: "Description complète", content: "Sangle douce à réglage micrométrique, boucle sécurisée, coloris apaisants. Pensé pour les premières semaines." },
      { title: "Matières & entretien", content: "Coton bio et polyester recyclé. Machine 30 °C." },
      { title: "Dimensions & tailles", content: "XS : 20–28 cm · S : 26–34 cm." },
    ],
    colors: [creme, vertSauge],
    sizes: [
      { name: "XS", stock: 15 },
      { name: "S", stock: 10 },
    ],
    gabarits: ["XS", "S"],
    isNew: true,
    curatedRank: 14,
    reviews: [],
    pairsWith: ["jouet-corde-galet"],
    tone: "cream",
  },
  {
    slug: "medaille-laiton",
    name: "Médaille gravée en laiton",
    brand: "Atelier Fauve",
    animal: "chien",
    subcategory: "colliers-harnais",
    price: 1900,
    shortDescription: "Laiton massif gravé en France, patine douce, silencieuse contre la boucle.",
    curatorNote: "Gravure profonde qui reste lisible des années — nous avons comparé douze fournisseurs avant de choisir celui-ci.",
    material: "Laiton",
    details: [
      { title: "Description complète", content: "Médaille ronde en laiton massif, gravure recto-verso incluse, anneau brisé renforcé." },
      { title: "Dimensions & tailles", content: "Taille unique — Ø 25 mm. Convient à tous les gabarits." },
    ],
    colors: [cuirCaramel],
    sizes: [{ name: "Taille unique", stock: 42 }],
    gabarits: ["XS", "S", "M", "L", "XL"],
    isNew: false,
    curatedRank: 22,
    reviews: [
      { author: "Marc P.", rating: 5, title: "Belle gravure", text: "Lisible, élégante, et elle ne tinte pas contre le collier. Parfait.", context: "Beagle, 12 kg", date: "2026-01-30", verified: true },
    ],
    pairsWith: ["collier-cuir-ambre"],
    tone: "caramel",
  },

  // ——— Chien · Laisses (3) ———
  {
    slug: "laisse-cuir-ambre",
    name: "Laisse Ambre en cuir pleine fleur",
    brand: "Atelier Fauve",
    animal: "chien",
    subcategory: "laisses",
    price: 6400,
    shortDescription: "L'assortie du collier Ambre : cuir plein, poignée roulée main, mousqueton forgé.",
    curatorNote: "La poignée roulée demande une heure de travail par laisse. C'est le genre de détail qu'on ne trouve plus.",
    material: "Cuir",
    details: [
      { title: "Description complète", content: "Cuir tannage végétal, poignée roulée cousue main, mousqueton en laiton forgé pivotant." },
      { title: "Matières & entretien", content: "Comme le collier Ambre : baume incolore deux fois par an." },
      { title: "Dimensions & tailles", content: "Longueur 120 cm, largeur 18 mm. Taille unique." },
    ],
    colors: [cuirCaramel, noirBrou],
    sizes: [{ name: "Taille unique", stock: 9 }],
    gabarits: ["S", "M", "L"],
    isNew: false,
    curatedRank: 5,
    reviews: [
      { author: "Camille R.", rating: 5, title: "Assortie et robuste", text: "Achetée avec le collier, l'ensemble est superbe. Le mousqueton inspire confiance.", context: "Berger australien, 24 kg", date: "2026-05-12", verified: true },
    ],
    pairsWith: ["collier-cuir-ambre"],
    tone: "caramel",
  },
  {
    slug: "laisse-trail-amarre",
    name: "Laisse de traction Amarre",
    brand: "Terre & Truffe",
    animal: "chien",
    subcategory: "laisses",
    price: 4900,
    shortDescription: "Corde dynamique avec amortisseur intégré et double mousqueton pour la rando mains libres.",
    curatorNote: "L'amortisseur absorbe vraiment les à-coups — validé avec un malinois de 32 kg en canicross.",
    material: "Corde & cuir",
    details: [
      { title: "Description complète", content: "Corde escalade 10 mm, section élastique gainée, deux mousquetons alu pour le portage ceinture." },
      { title: "Dimensions & tailles", content: "Longueur 110–140 cm selon réglage. Taille unique." },
    ],
    colors: [vertSauge, terracotta],
    sizes: [{ name: "Taille unique", stock: 7 }],
    gabarits: ["M", "L", "XL"],
    isNew: true,
    curatedRank: 11,
    reviews: [],
    pairsWith: ["harnais-randonnee-sequoia"],
    tone: "sage",
  },
  {
    slug: "laisse-tressee-olive",
    name: "Laisse tressée Olive",
    brand: "Maison Bergame",
    animal: "chien",
    subcategory: "laisses",
    price: 4600,
    shortDescription: "Corde marine et cuir, légère en main, assortie au collier tressé Olive.",
    curatorNote: "Le tressage huit brins ne vrille pas — même après un an d'enrouleurs et de nœuds.",
    material: "Corde & cuir",
    details: [
      { title: "Description complète", content: "Tressage huit brins, épissures main, renforts cuir aux extrémités, mousqueton laiton." },
      { title: "Dimensions & tailles", content: "Longueur 130 cm, Ø 10 mm. Taille unique." },
    ],
    colors: [vertSauge, terracotta, creme],
    sizes: [{ name: "Taille unique", stock: 13 }],
    gabarits: ["S", "M", "L"],
    isNew: false,
    curatedRank: 15,
    reviews: [],
    pairsWith: ["collier-tresse-olive"],
    tone: "sage",
  },

  // ——— Chien · Couchages & Paniers (3) ———
  {
    slug: "panier-laine-nid",
    name: "Panier Nid en laine bouillie",
    brand: "Maison Bergame",
    animal: "chien",
    subcategory: "couchages-paniers",
    price: 12900,
    shortDescription: "Laine bouillie moulée, bords enveloppants, coussin déhoussable en lin lavé.",
    curatorNote: "La laine régule naturellement la température — les chiens l'adoptent hiver comme été. Le nôtre a trois ans et tient parfaitement sa forme.",
    material: "Laine",
    details: [
      { title: "Description complète", content: "Coque en laine bouillie thermoformée, coussin réversible lin/laine, antidérapant discret." },
      { title: "Matières & entretien", content: "Laine européenne, lin lavé. Housse machine 30 °C, coque à brosser." },
      { title: "Dimensions & tailles", content: "S : Ø 50 cm · M : Ø 65 cm · L : Ø 80 cm." },
    ],
    colors: [grege, vertSauge],
    sizes: [
      { name: "S", stock: 6 },
      { name: "M", stock: 4 },
      { name: "L", stock: 2 },
    ],
    gabarits: ["XS", "S", "M", "L"],
    isNew: false,
    curatedRank: 3,
    reviews: [
      { author: "Élise T.", rating: 5, title: "Adopté en une nuit", text: "Notre whippet frileux ne dort plus ailleurs. Et c'est le seul panier que j'accepte dans le salon.", context: "Whippet, 12 kg — taille M", date: "2026-06-02", verified: true },
      { author: "Hugo V.", rating: 4, title: "Très qualitatif", text: "Superbe matière. Prévoir la taille au-dessus si votre chien aime s'étaler.", context: "Golden retriever, 30 kg — taille L", date: "2026-04-15", verified: true },
    ],
    pairsWith: ["plaid-refuge"],
    tone: "cream",
  },
  {
    slug: "matelas-voyage-bivouac",
    name: "Matelas de voyage Bivouac",
    brand: "Terre & Truffe",
    animal: "chien",
    subcategory: "couchages-paniers",
    price: 6900,
    shortDescription: "Se roule et se sangle en 10 secondes : le couchage isolant des week-ends et du coffre.",
    curatorNote: "Dessous étanche, dessus chaud, roulé il tient dans une sacoche de vélo. L'accessoire le plus prêté de la rédaction.",
    material: "Textile technique",
    details: [
      { title: "Description complète", content: "Mousse isolante, dessus polaire recyclée, dessous ripstop étanche, sangle de portage cuir." },
      { title: "Dimensions & tailles", content: "M : 70 × 50 cm · L : 95 × 65 cm." },
    ],
    colors: [vertSauge, noirBrou],
    sizes: [
      { name: "M", stock: 8 },
      { name: "L", stock: 5 },
    ],
    gabarits: ["S", "M", "L"],
    isNew: true,
    curatedRank: 12,
    reviews: [],
    pairsWith: ["harnais-randonnee-sequoia"],
    tone: "sage",
  },
  {
    slug: "plaid-refuge",
    name: "Plaid Refuge en laine recyclée",
    brand: "Maison Bergame",
    animal: "chien",
    subcategory: "couchages-paniers",
    price: 4500,
    shortDescription: "Protège canapé et sièges auto avec l'allure d'un plaid de maison de famille.",
    curatorNote: "Assez beau pour rester sur le canapé quand les invités arrivent — c'était notre cahier des charges.",
    material: "Laine",
    details: [
      { title: "Description complète", content: "Laine recyclée tissée en Occitanie, finition frangée, résiste aux griffes." },
      { title: "Dimensions & tailles", content: "Taille unique — 140 × 110 cm. Convient à tous les gabarits." },
    ],
    colors: [grege, terracotta],
    sizes: [{ name: "Taille unique", stock: 18 }],
    gabarits: ["XS", "S", "M", "L", "XL"],
    isNew: false,
    curatedRank: 17,
    reviews: [],
    pairsWith: ["panier-laine-nid"],
    tone: "terracotta",
  },

  // ——— Chien · Jouets (2) ———
  {
    slug: "jouet-corde-galet",
    name: "Jouet de traction Galet",
    brand: "Petit Clan",
    animal: "chien",
    subcategory: "jouets",
    price: 1800,
    shortDescription: "Corde de coton recyclé nouée serrée autour d'un cœur en caoutchouc naturel.",
    curatorNote: "Il survit à un jack russell destructeur depuis quatre mois — notre record interne.",
    material: "Coton & caoutchouc",
    details: [
      { title: "Description complète", content: "Nœuds serrés main, cœur en hévéa, teintures végétales sans risque à la mâche." },
      { title: "Dimensions & tailles", content: "S : 18 cm · M : 26 cm." },
    ],
    colors: [terracotta, vertSauge],
    sizes: [
      { name: "S", stock: 20 },
      { name: "M", stock: 14 },
    ],
    gabarits: ["XS", "S", "M"],
    isNew: false,
    curatedRank: 19,
    reviews: [
      { author: "Nadia K.", rating: 5, title: "Incassable (pour l'instant)", text: "Premier jouet qui passe la semaine. Les couleurs sont très jolies.", context: "Jack russell, 7 kg — taille S", date: "2026-03-08", verified: true },
    ],
    pairsWith: [],
    tone: "terracotta",
  },
  {
    slug: "jouet-fouille-truffe",
    name: "Tapis de fouille Truffe",
    brand: "Petit Clan",
    animal: "chien",
    subcategory: "jouets",
    price: 3400,
    shortDescription: "Un tapis de léchage et de fouille en feutre dense pour occuper les museaux curieux.",
    curatorNote: "Quinze minutes de fouille fatiguent autant qu'une demi-heure de balade — validé par notre éducatrice.",
    material: "Feutre",
    details: [
      { title: "Description complète", content: "Feutre de laine dense, poches et replis variés, antidérapant. Machine 30 °C." },
      { title: "Dimensions & tailles", content: "Taille unique — 45 × 35 cm. Convient à tous les gabarits." },
    ],
    colors: [grege, vertSauge],
    sizes: [{ name: "Taille unique", stock: 11 }],
    gabarits: ["XS", "S", "M", "L", "XL"],
    isNew: true,
    curatedRank: 13,
    reviews: [],
    pairsWith: ["jouet-corde-galet"],
    tone: "cream",
  },

  // ——— Chat · Couchages & Cocons (3) ———
  {
    slug: "cocon-feutre-alcove",
    name: "Cocon Alcôve en feutre de laine",
    brand: "Casa Felis",
    animal: "chat",
    subcategory: "couchages-cocons",
    price: 9800,
    shortDescription: "Une grotte de feutre moulé où votre chat disparaît des heures. Coussin lin déhoussable.",
    curatorNote: "Les chats anxieux l'adoptent immédiatement : l'entrée resserrée et l'épaisseur du feutre créent un vrai refuge.",
    material: "Laine",
    details: [
      { title: "Description complète", content: "Feutre de laine 8 mm thermoformé, structure autoportante, coussin réversible." },
      { title: "Matières & entretien", content: "Laine mérinos, lin lavé. Brossage et aération ; housse machine 30 °C." },
      { title: "Dimensions & tailles", content: "Taille unique — Ø 40 cm, hauteur 30 cm. Chats jusqu'à 7 kg." },
    ],
    colors: [grege, vertSauge],
    sizes: [{ name: "Taille unique", stock: 7 }],
    gabarits: ["XS", "S"],
    isNew: false,
    curatedRank: 4,
    reviews: [
      { author: "Léa F.", rating: 5, title: "Il y vit", text: "Mon maine coon squattait les placards, maintenant c'est l'alcôve. Très belle qualité de feutre.", context: "Maine coon, 6 kg", date: "2026-05-28", verified: true },
    ],
    pairsWith: ["plaid-refuge"],
    tone: "cream",
  },
  {
    slug: "coussin-fenetre-vigie",
    name: "Coussin de fenêtre Vigie",
    brand: "Casa Felis",
    animal: "chat",
    subcategory: "couchages-cocons",
    price: 5600,
    shortDescription: "S'installe sur le rebord de fenêtre sans percer : le poste d'observation préféré des chats d'appartement.",
    curatorNote: "Le système de maintien ne marque pas le bois et supporte 15 kg — testé sur nos propres fenêtres.",
    material: "Laine",
    details: [
      { title: "Description complète", content: "Plateau rigide gainé de lainage, fixation par tension réglable, housse zippée." },
      { title: "Dimensions & tailles", content: "Taille unique — 55 × 30 cm. Rebords de 2 à 20 cm." },
    ],
    colors: [grege, terracotta],
    sizes: [{ name: "Taille unique", stock: 0 }],
    gabarits: ["XS", "S"],
    isNew: false,
    curatedRank: 16,
    reviews: [],
    pairsWith: ["cocon-feutre-alcove"],
    tone: "terracotta",
  },
  {
    slug: "hamac-radiateur-perchoir",
    name: "Hamac de radiateur Perchoir",
    brand: "Casa Felis",
    animal: "chat",
    subcategory: "couchages-cocons",
    price: 4400,
    shortDescription: "Structure hêtre massif et toile lainage : la sieste au chaud, sans housse qui glisse.",
    curatorNote: "Le seul hamac stable que nous ayons trouvé : le cadre en bois ne plie pas et la toile se retend d'un geste.",
    material: "Bois & laine",
    details: [
      { title: "Description complète", content: "Cadre hêtre huilé, toile amovible, crochets gainés compatibles radiateurs standard." },
      { title: "Dimensions & tailles", content: "Taille unique — 45 × 30 cm. Chats jusqu'à 8 kg." },
    ],
    colors: [grege],
    sizes: [{ name: "Taille unique", stock: 9 }],
    gabarits: ["XS", "S"],
    isNew: true,
    curatedRank: 18,
    reviews: [],
    pairsWith: ["cocon-feutre-alcove"],
    tone: "cream",
  },

  // ——— Chat · Arbres & Griffoirs (2) ———
  {
    slug: "griffoir-bouleau-totem",
    name: "Griffoir Totem en bouleau",
    brand: "Casa Felis",
    animal: "chat",
    subcategory: "arbres-a-chat-griffoirs",
    price: 11900,
    shortDescription: "Colonne de sisal serré sur socle bouleau lesté : stable même pour les grands gabarits.",
    curatorNote: "Le sisal est remplaçable — on change la corde, pas le griffoir. Une aberration que ce ne soit pas le standard.",
    material: "Bois & sisal",
    details: [
      { title: "Description complète", content: "Socle bouleau multiplis lesté, colonne Ø 12 cm, sisal naturel remplaçable, hauteur 80 cm." },
      { title: "Dimensions & tailles", content: "Taille unique — H 80 cm, socle 40 × 40 cm." },
    ],
    colors: [creme],
    sizes: [{ name: "Taille unique", stock: 5 }],
    gabarits: ["XS", "S", "M"],
    isNew: false,
    curatedRank: 6,
    reviews: [
      { author: "Paul G.", rating: 5, title: "Enfin stable", text: "Mon chat de 7 kg s'y jette dessus, rien ne bouge. Le sisal remplaçable est un vrai plus.", context: "Européen, 7 kg", date: "2026-06-10", verified: true },
    ],
    pairsWith: ["jouet-plume-comete"],
    tone: "cream",
  },
  {
    slug: "arbre-mural-corniche",
    name: "Parcours mural Corniche",
    brand: "Casa Felis",
    animal: "chat",
    subcategory: "arbres-a-chat-griffoirs",
    price: 15900,
    shortDescription: "Trois marches en chêne et un plateau feutré qui transforment un mur en parcours d'escalade.",
    curatorNote: "Dessiné par un ébéniste avec une comportementaliste féline : hauteurs et espacements sont calculés, pas décoratifs.",
    material: "Bois & laine",
    details: [
      { title: "Description complète", content: "Chêne massif huilé, fixations invisibles fournies, plateau supérieur feutré. Charge 12 kg par marche." },
      { title: "Dimensions & tailles", content: "Taille unique — 3 marches 35 × 20 cm + plateau 45 × 30 cm." },
    ],
    colors: [cuirCaramel, creme],
    sizes: [{ name: "Taille unique", stock: 3 }],
    gabarits: ["XS", "S", "M"],
    isNew: true,
    curatedRank: 7,
    reviews: [],
    pairsWith: ["griffoir-bouleau-totem"],
    tone: "caramel",
  },

  // ——— Chat · Jouets (2) ———
  {
    slug: "jouet-plume-comete",
    name: "Plumeau Comète",
    brand: "Petit Clan",
    animal: "chat",
    subcategory: "jouets",
    price: 1600,
    shortDescription: "Manche hêtre, cordon élastique et plumes naturelles interchangeables.",
    curatorNote: "Les recharges évitent de racheter un jouet entier quand les plumes rendent l'âme — sobre et malin.",
    material: "Bois & plumes",
    details: [
      { title: "Description complète", content: "Manche hêtre 40 cm, cordon élastique gainé, embout à recharge plumes ou liège." },
      { title: "Dimensions & tailles", content: "Taille unique." },
    ],
    colors: [creme, terracotta],
    sizes: [{ name: "Taille unique", stock: 25 }],
    gabarits: ["XS", "S"],
    isNew: false,
    curatedRank: 20,
    reviews: [
      { author: "Inès B.", rating: 4, title: "Session garantie", text: "Dix minutes de folie chaque soir. J'aurais aimé une plume de rechange incluse.", context: "Chartreux, 5 kg", date: "2026-02-14", verified: true },
    ],
    pairsWith: ["balle-liege-duo"],
    tone: "terracotta",
  },
  {
    slug: "balle-liege-duo",
    name: "Duo de balles en liège",
    brand: "Petit Clan",
    animal: "chat",
    subcategory: "jouets",
    price: 1200,
    shortDescription: "Légères, silencieuses, agréables à griffer : les balles que les chats préfèrent aux grelots.",
    curatorNote: "Silencieuses sur le parquet à 6 h du matin. Les humains de l'équipe valident autant que les chats.",
    material: "Liège",
    details: [
      { title: "Description complète", content: "Liège naturel poncé, Ø 4 cm, sans traitement. Lot de deux." },
      { title: "Dimensions & tailles", content: "Taille unique — Ø 4 cm." },
    ],
    colors: [creme],
    sizes: [{ name: "Taille unique", stock: 30 }],
    gabarits: ["XS", "S"],
    isNew: false,
    curatedRank: 23,
    reviews: [],
    pairsWith: ["jouet-plume-comete"],
    tone: "cream",
  },

  // ——— NAC · Habitat & Couchage (3) ———
  {
    slug: "cabane-pin-terrier",
    name: "Cabane Terrier en pin non traité",
    brand: "Petit Clan",
    animal: "nac",
    subcategory: "habitat-couchage",
    price: 5400,
    shortDescription: "Deux entrées, un toit plat renforcé pour l'observation : la cabane préférée des lapins.",
    curatorNote: "Pin brut sans colle ni vernis — rongeable sans risque, ce qui est étonnamment rare.",
    material: "Bois",
    details: [
      { title: "Description complète", content: "Pin massif non traité, assemblage tenons-mortaises sans colle, toit plat charge 5 kg." },
      { title: "Dimensions & tailles", content: "M : 30 × 22 × 18 cm · L : 42 × 30 × 24 cm." },
    ],
    colors: [creme],
    sizes: [
      { name: "M", stock: 10 },
      { name: "L", stock: 6 },
    ],
    gabarits: ["XS", "S"],
    isNew: false,
    curatedRank: 10,
    reviews: [
      { author: "Chloé M.", rating: 5, title: "Rongée avec amour", text: "Mes deux lapins dorment dedans et rongent les angles sans danger. Très solide.", context: "Lapins béliers, 2 kg", date: "2026-04-22", verified: true },
    ],
    pairsWith: ["tapis-chanvre-prairie"],
    tone: "cream",
  },
  {
    slug: "tapis-chanvre-prairie",
    name: "Tapis Prairie en chanvre",
    brand: "Petit Clan",
    animal: "nac",
    subcategory: "habitat-couchage",
    price: 2400,
    shortDescription: "Fibre de chanvre absorbante et rongeable pour le fond d'habitat ou l'aire de jeu.",
    curatorNote: "Remplace la moquette synthétique, dangereuse à l'ingestion. Compostable en fin de vie.",
    material: "Chanvre",
    details: [
      { title: "Description complète", content: "Chanvre naturel non traité, tissage dense, découpable aux ciseaux." },
      { title: "Dimensions & tailles", content: "S : 40 × 30 cm · M : 60 × 40 cm." },
    ],
    colors: [creme],
    sizes: [
      { name: "S", stock: 16 },
      { name: "M", stock: 12 },
    ],
    gabarits: ["XS", "S"],
    isNew: false,
    curatedRank: 21,
    reviews: [],
    pairsWith: ["cabane-pin-terrier"],
    tone: "cream",
  },
  {
    slug: "dome-foin-refuge",
    name: "Dôme de foin Refuge",
    brand: "Petit Clan",
    animal: "nac",
    subcategory: "habitat-couchage",
    price: 1900,
    shortDescription: "Un dôme tressé en foin de Crau, abri et en-cas à la fois.",
    curatorNote: "Foin AOP de la Crau, tressé serré : il tient plusieurs semaines même face à des cochons d'Inde motivés.",
    material: "Foin",
    details: [
      { title: "Description complète", content: "Foin de Crau AOP tressé main, sans fil métallique ni colle. Entièrement comestible." },
      { title: "Dimensions & tailles", content: "Taille unique — Ø 22 cm, entrée 9 cm." },
    ],
    colors: [creme],
    sizes: [{ name: "Taille unique", stock: 14 }],
    gabarits: ["XS"],
    isNew: true,
    curatedRank: 24,
    reviews: [],
    pairsWith: ["tapis-chanvre-prairie"],
    tone: "caramel",
  },
];
