import type { Product, ProductColor, ProductVariant, Subcategory } from "./types";
import type { Brand } from "./types";
import { sizesForBrand } from "./brands";

/**
 * Catalogue — 13 modèles, 5 marques, 88 coloris (D-053, jalon 3).
 *
 * Données issues du dossier « Catalogue produits — fiches complètes » du
 * 21/08/2026, lui-même sourcé sur les pages officielles des marques. Rien
 * n'est extrapolé : lorsqu'une marque ne publie pas une donnée, la fiche
 * porte « Non communiqué par la marque » ou une mesure de laboratoire
 * indépendant explicitement signalée comme telle.
 *
 * ⚠️ Deux réserves portées par le document source et conservées ici :
 * - les **noms de coloris sont descriptifs**, établis à partir des photos, et
 *   ne sont pas des dénominations officielles de marque (sauf Salomon XT-6,
 *   recoupée avec les pages officielles) — à confirmer sur l'étiquette de
 *   boîte avant mise en ligne ;
 * - `reviews` est **vide partout**, et doit le rester tant qu'aucun achat
 *   vérifié n'a eu lieu (audit 2026-08, MO-7 : 14 avis fictifs retirés au
 *   titre de l'art. L.121-4).
 *
 * Le **stock est de démonstration** (H33) : déterministe, reproductible, mais
 * fictif. Il doit être remplacé par l'inventaire réel avant toute vente.
 */

export const subcategories: Subcategory[] = [
  { brand: "on", slug: "running", label: "Running route", description: "Les deux daily trainers d'On : amorti maximal, géométries CloudTec et déroulé du pied travaillé pour la distance." },
  { brand: "on", slug: "lifestyle", label: "Marche urbaine", description: "La gamme Active Life — pensée pour la station debout prolongée, le voyage et le port quotidien. Ce ne sont pas des chaussures de running." },
  { brand: "nike", slug: "lifestyle", label: "Lifestyle", description: "Quatre silhouettes, quatre décennies. Trois reposent sur une unité Air ; la P-6000 n'en a pas." },
  { brand: "saucony", slug: "lifestyle", label: "Originals", description: "Deux rééditions d'archive. Les mentions de stabilité appartiennent à leur passé running et n'ont plus de valeur prescriptive." },
  { brand: "asics", slug: "sportstyle", label: "SportStyle", description: "Deux rééditions de la gamme SportStyle — à ne pas confondre avec les GEL-KAYANO de running actuelles." },
  { brand: "salomon", slug: "sportstyle", label: "Sportstyle", description: "L'héritage trail passé en ville : équipement technique complet, deux coloris doublés GORE-TEX." },
];

/**
 * Pointures proposées : la plage 36–45 du dossier fournisseur, intersectée
 * avec la grille de la marque. Salomon travaille en tiers de pointure, Nike
 * et ASICS en demies — d'où l'intersection plutôt qu'une plage codée en dur.
 */
function offeredSizes(brand: Brand): string[] {
  return sizesForBrand(brand).filter((size) => {
    const value = Number(size);
    return value >= 36 && value <= 45;
  });
}

/**
 * Stock de démonstration (H33). Déterministe — la même clé rend toujours la
 * même valeur — pour que le catalogue de démonstration soit reproductible
 * entre deux démarrages, et pour qu'environ un cinquième des variantes soit
 * en rupture : c'est ce qui exerce le chemin « Bientôt de retour » et le
 * formulaire d'alerte de retour en stock. Aucun rapport avec un inventaire.
 */
function demoStock(slug: string, color: string, size: string): number {
  const key = `${slug}|${color}|${size}`;
  let hash = 0;
  for (let i = 0; i < key.length; i += 1) {
    hash = (hash * 31 + key.charCodeAt(i)) >>> 0;
  }
  const roll = hash % 10;
  return roll < 2 ? 0 : roll - 1;
}

function variantsFor(slug: string, brand: Brand, colors: ProductColor[]): ProductVariant[] {
  const sizes = offeredSizes(brand);
  return colors.flatMap((color) =>
    sizes.map((size) => ({
      color: color.name,
      size,
      stock: demoStock(slug, color.name, size),
    })),
  );
}

/** Les variantes sont dérivées des coloris et de la grille de la marque. */
function model(product: Omit<Product, "variants">): Product {
  return { ...product, variants: variantsFor(product.slug, product.brand, product.colors) };
}

export const products: Product[] = [
  model({
    slug: "cloudmonster-3",
    name: "On Cloudmonster 3",
    brand: "on",
    subcategory: "running",
    genres: ["mixte"],
    price: 4999,
    shortDescription: "Le monstre d'amorti d'On. Triple couche de CloudTec®, mousse Helion™ double densité et plaque Speedboard® en nylon : c'est la sensation de rebond la plus marquée de toute la gamme On.",
    curatorNote: "La pile d'amorti la plus haute du catalogue On, et la plus démonstrative : les Clouds hexagonaux se compriment à la verticale et à l'horizontale. Nous la situons sur les sorties longues et les jours de récupération — pas sur le travail au seuil, ce que la marque elle-même indique.",
    material: "Mesh technique",
    details: [
      { title: "Description complète", content: "Sortie le 5 mars 2026, la Cloudmonster 3 est le daily trainer maximaliste d'On : une pile d'amorti généreuse, une géométrie de bascule (rocker) très prononcée, et une restitution d'énergie franche à chaque appui. Les gros « Clouds » hexagonaux visibles sur le flanc ne sont pas décoratifs — ils se compriment verticalement ET horizontalement pour encaisser l'impact puis relancer le pied vers l'avant.\n\nLa troisième génération resserre le chaussant par rapport à la Cloudmonster 2 et épaissit nettement le rembourrage de la languette (5,3 mm contre 1,5 mm). La tige en mesh technique reste respirante, avec des renforts placés uniquement là où c'est utile. La semelle extérieure en gomme compressée à gros pods assure l'accroche sur bitume mouillé.\n\nC'est la chaussure des sorties longues et des jours de récupération : du 10 km au marathon, foulée neutre. Elle est en revanche moins à l'aise sur les séances rapides et le travail au seuil — sa vocation est le confort et l'endurance, pas la vivacité." },
    ],
    colors: [
      { name: "Vert d'eau / menthe, logo vert fluo", hex: "#8FBFB4", images: ["/produits/cloudmonster-3/1.jpg"] },
      { name: "Blanc / bleu ciel", hex: "#F1F0EE", images: ["/produits/cloudmonster-3/2.jpg"] },
      { name: "Blanc / gris clair", hex: "#F1F0EE", images: ["/produits/cloudmonster-3/3.jpg"] },
      { name: "Jaune citron / semelle crème", hex: "#E4DE4A", images: ["/produits/cloudmonster-3/4.jpg"] },
      { name: "Blanc / lilas pâle", hex: "#F1F0EE", images: ["/produits/cloudmonster-3/5.jpg"] },
      { name: "Gris-bleu / semelle crème", hex: "#8E9AA6", images: ["/produits/cloudmonster-3/6.jpg"] },
      { name: "Blanc gris / semelle rose framboise", hex: "#D8D8D6", images: ["/produits/cloudmonster-3/7.jpg"] },
      { name: "Blanc / talon noir", hex: "#F1F0EE", images: ["/produits/cloudmonster-3/8.jpg"] },
      { name: "Violet indigo / semelle blanche", hex: "#3F3260", images: ["/produits/cloudmonster-3/9.jpg"] },
      { name: "Blanc intégral", hex: "#F1F0EE", images: ["/produits/cloudmonster-3/10.jpg"] },
      { name: "Noir intégral", hex: "#1C1C1E", images: ["/produits/cloudmonster-3/11.jpg"] },
    ],
    sizeAdvice: "Taille normalement (« correspond à la pointure réelle », mention officielle On). Le chaussant est cependant plus étroit que celui de la Cloudmonster 2 : avant-pied mesuré à 71,0 mm contre 74,5 mm sur la génération précédente, et volume de cou-de-pied bas. Pied large ou cambrure marquée : prendre une demi-pointure au-dessus, ou orienter vers la déclinaison Wide.",
    isNew: true,
    curatedRank: 4,
    reviews: [],
    pairsWith: ["cloudsurfer-max", "cloudtilt", "cloudtilt-remix"],
    tone: "signal",
    features: [
      "CloudTec® triple couche : la plus grosse pile d'amorti du catalogue On",
      "Mousse Helion™ double densité, retour d'énergie très marqué",
      "Plaque Speedboard® en nylon pour la propulsion",
      "Rocker prononcé : déroulé du pied fluide et rapide",
      "Languette semi-gousset très rembourrée (5,3 mm)",
      "Drop 6 mm — proche du sol malgré la hauteur d'amorti",
    ],
    specifications: [
      { label: "Catégorie", value: "Running route — daily trainer à amorti maximal" },
      { label: "Année de sortie", value: "2026 (5 mars 2026, lancement mondial)" },
      { label: "Poids", value: "295 g (homme, US 8.5) — 240 g (femme, US 7). Données officielles On." },
      { label: "Drop", value: "6 mm" },
      { label: "Hauteurs de semelle", value: "Talon 35 mm / avant-pied 29 mm (mesure officielle On, hors semelle de propreté). Les revendeurs annoncent 40 / 34 mm, mesure semelle de propreté incluse." },
      { label: "Tige", value: "Mesh technique respirant, renforts stratégiques, languette semi-gousset rembourrée (5,3 mm). Matière déclarée : polyester recyclé." },
      { label: "Semelle intermédiaire", value: "Mousse Helion™ double densité + CloudTec® triple couche + Speedboard® nylon" },
      { label: "Semelle extérieure", value: "Gomme compressée, dessin à 10 gros pods avec canal central, épaisseur ≈ 3,2 mm" },
      { label: "Semelle de propreté", value: "EVA amovible, ≈ 4,4 mm" },
      { label: "Usage", value: "Route et bitume, foulée neutre. 10 km à marathon, sorties longues, récupération, allure constante." },
      { label: "Largeurs disponibles", value: "Narrow / Normal / Wide (selon les coloris)" },
      { label: "Fabrication", value: "Viêt Nam" },
      { label: "Prix public conseillé On", value: "200 € TTC" },
    ],
  }),
  model({
    slug: "cloudsurfer-max",
    name: "On Cloudsurfer Max",
    brand: "on",
    subcategory: "running",
    genres: ["mixte"],
    price: 4999,
    shortDescription: "L'option la plus moelleuse de la famille Surfer. Double couche de CloudTec Phase® et mousse Helion™ ultra-douce, taillée pour les sorties de 15 km et plus.",
    curatorNote: "L'amorti maximal d'On sans la nervosité : les Clouds inclinés se compriment en séquence et le déroulé talon-pointe se fait rouler. On la déconseille explicitement pour les séances rapides ; nous la présentons donc pour ce qu'elle est, une chaussure de distance.",
    material: "Mesh technique",
    details: [
      { title: "Description complète", content: "Lancée le 17 juillet 2025, la Cloudsurfer Max pousse le principe du CloudTec Phase® à son maximum : les « Clouds » sont inclinés et se compriment séquentiellement, comme une rangée de dominos. Le résultat est une transition talon-pointe roulée, presque sans à-coups, qui explique la sensation très douce sous le pied.\n\nContrairement à la Cloudmonster, elle ne comporte pas de plaque Speedboard®. C'est un choix assumé : ici l'objectif est le confort sur la durée, pas la relance. La tige a été retravaillée avec un col en tricot plat et un empiècement de laçage revu, avec des œillets textiles qui répartissent mieux la pression du serrage.\n\nChaussure de sorties longues, de récupération et d'allure constante. Sa masse et son amorti profond en font aussi une bonne option pour les gabarits plus lourds. En revanche, elle n'est pas faite pour les séances rapides." },
    ],
    colors: [
      { name: "Blanc → rose dégradé, semelle rose", hex: "#F1F0EE", images: ["/produits/cloudsurfer-max/1.jpg"] },
      { name: "Bleu-violet dégradé, semelle lavande", hex: "#7B76B8", images: ["/produits/cloudsurfer-max/2.jpg"] },
      { name: "Blanc / rose, accents framboise", hex: "#F1F0EE", images: ["/produits/cloudsurfer-max/3.jpg"] },
      { name: "Blanc / vert d'eau, logo vert", hex: "#F1F0EE", images: ["/produits/cloudsurfer-max/4.jpg"] },
      { name: "Noir / vert foncé, semelle grise", hex: "#1C1C1E", images: ["/produits/cloudsurfer-max/5.jpg"] },
      { name: "Blanc intégral", hex: "#F1F0EE", images: ["/produits/cloudsurfer-max/6.jpg"] },
    ],
    sizeAdvice: "Taille normalement (mention officielle On). Avant-pied plutôt effilé (71,4 mm mesurés, contre 73,2 mm de moyenne sur le marché) mais bon volume général, ce qui reste confortable quand le pied gonfle sur longue distance. Deux points de vigilance relevés en test : une gêne possible sur le dessus du pied au niveau de la languette si le serrage est trop fort, et une respirabilité modeste.",
    isNew: false,
    curatedRank: 10,
    reviews: [],
    pairsWith: ["cloudmonster-3", "cloudtilt", "cloudtilt-remix"],
    tone: "chalk",
    features: [
      "CloudTec Phase® double couche : compression séquentielle « en dominos »",
      "Mousse Helion™ dans sa version la plus douce",
      "Col en tricot plat et œillets textiles : serrage progressif, sans point dur",
      "Conçue pour les sorties de 15 km et plus",
      "Version Wide disponible au catalogue On",
      "Drop 6 mm, stack 36 / 30 mm",
    ],
    specifications: [
      { label: "Catégorie", value: "Running route — amorti maximal, longue distance" },
      { label: "Année de sortie", value: "2025 (17 juillet 2025)" },
      { label: "Poids", value: "313 g (homme, US 10) — 245 g (femme, US 7.5). Données officielles On." },
      { label: "Drop", value: "6 mm (officiel On). Un test en laboratoire indépendant mesure 7,9 mm." },
      { label: "Hauteurs de semelle", value: "Talon 36 mm / avant-pied 30 mm (officiel On)" },
      { label: "Tige", value: "Mesh technique, empiècement de laçage retravaillé, col en tricot plat, languette semi-gousset. Matière déclarée : polyester recyclé." },
      { label: "Semelle intermédiaire", value: "Mousse Helion™ + CloudTec Phase® double couche. Pas de Speedboard®." },
      { label: "Semelle extérieure", value: "Gomme segmentée, découpes à l’avant-pied, canal central talon-pointe, épaisseur ≈ 3,2 mm" },
      { label: "Semelle de propreté", value: "Amovible, ≈ 3,1 mm" },
      { label: "Usage", value: "Route, foulée neutre. Sorties longues (15 km et +), récupération, allure constante. Déconseillée pour le travail à haute intensité." },
      { label: "Largeurs disponibles", value: "Normal et Wide" },
      { label: "Fabrication", value: "Viêt Nam" },
      { label: "Prix public conseillé On", value: "190 € TTC" },
    ],
  }),
  model({
    slug: "cloudtilt",
    name: "On Cloudtilt",
    brand: "on",
    subcategory: "lifestyle",
    genres: ["mixte"],
    price: 4999,
    shortDescription: "L'amorti On, pensé pour la ville. Ultra-légère, laçage rapide élastique, tige 100 % polyester recyclé : la chaussure des journées debout.",
    curatorNote: "Une chaussure de marche urbaine assumée, pas une running déguisée. La gamme Active Life vise la station debout prolongée, le voyage et le port quotidien — c'est écrit sur la fiche officielle et nous préférons le répéter ici.",
    material: "Mesh technique",
    details: [
      { title: "Description complète", content: "Sortie en 2024, la Cloudtilt n'est pas une chaussure de running — On la classe explicitement dans sa gamme « Active Life ». Elle reprend l'amorti CloudTec Phase® et la mousse Helion™ des modèles route, mais dans une silhouette épurée, sans surpiqûres apparentes, avec un système de laçage rapide de type élastique qui permet de l'enfiler d'un geste.\n\nC'est sa tige qui la distingue : On déclare 100 % de polyester recyclé sur l'empeigne, la languette, la doublure d'empeigne et la doublure de col — la revendication matière la plus complète de toute la gamme. Le mesh est teint dans la masse (procédé dope-dyed), ce qui réduit fortement la consommation d'eau à la fabrication.\n\nCible : marche urbaine, voyage, station debout prolongée, métiers qui passent la journée sur leurs pieds. Son maintien du talon est volontairement souple et sa respirabilité modeste — ce n'est pas une chaussure de forte chaleur ni de course." },
    ],
    colors: [
      { name: "Blanc / gris clair", hex: "#F1F0EE", images: ["/produits/cloudtilt/1.jpg"] },
      { name: "Noir intégral", hex: "#1C1C1E", images: ["/produits/cloudtilt/2.jpg"] },
      { name: "Bleu ciel / vert d'eau dégradé", hex: "#9FC7E0", images: ["/produits/cloudtilt/3.jpg"] },
      { name: "Beige sable / crème", hex: "#D8C7AA", images: ["/produits/cloudtilt/4.jpg"] },
      { name: "Rose poudré / bordeaux", hex: "#E3BFC4", images: ["/produits/cloudtilt/5.jpg"] },
      { name: "Blanc → anthracite dégradé", hex: "#F1F0EE", images: ["/produits/cloudtilt/6.jpg"] },
      { name: "Turquoise / blanc", hex: "#3FB8AE", images: ["/produits/cloudtilt/7.jpg"] },
      { name: "Noir / rouge dégradé", hex: "#1C1C1E", images: ["/produits/cloudtilt/8.jpg"] },
      { name: "Lilas / rose pâle", hex: "#BFA8D4", images: ["/produits/cloudtilt/9.jpg"] },
    ],
    sizeAdvice: "Taille normalement (mention officielle On), confirmé par un large volume d'avis utilisateurs. Largeur médiane, avant-pied légèrement arrondi. Deux points à signaler en fiche : le maintien du talon est souple, et la respirabilité est faible — à déconseiller pour un usage en plein été.",
    isNew: false,
    curatedRank: 8,
    reviews: [],
    pairsWith: ["cloudmonster-3", "cloudsurfer-max", "cloudtilt-remix"],
    tone: "sand",
    features: [
      "Amorti CloudTec Phase® + mousse Helion™",
      "Laçage rapide élastique : on l'enfile sans se baisser",
      "Tige 100 % polyester recyclé (déclaration officielle On)",
      "Mesh teint dans la masse : environ 90 % d'eau économisée",
      "Silhouette sans couture apparente, très épurée",
      "Pensée pour la marche et la station debout, pas pour la course",
    ],
    specifications: [
      { label: "Catégorie", value: "Lifestyle / marche urbaine — gamme Active Life On" },
      { label: "Année de sortie", value: "2024" },
      { label: "Poids", value: "Non publié par On. Mesure en laboratoire indépendant : ≈ 266 g (homme, US 9). D'autres sources annoncent 229 g et 303 g — pointure de référence inconnue." },
      { label: "Drop", value: "≈ 7 mm (donnée revendeur ; non publiée sur on.com). Mesure laboratoire : 8,7 mm." },
      { label: "Hauteurs de semelle", value: "Non publiées par On. Mesure laboratoire : talon 35,5 mm / avant-pied 26,8 mm." },
      { label: "Tige", value: "Mesh technique tissé serré, teint dans la masse. Empeigne, languette, doublure d’empeigne et doublure de col : 100 % polyester recyclé (déclaration officielle On)." },
      { label: "Semelle intermédiaire", value: "CloudTec Phase® + mousse Helion™" },
      { label: "Semelle extérieure", value: "Gomme en couverture partielle, composé dur, épaisseur ≈ 3,1 mm" },
      { label: "Semelle de propreté", value: "Amovible, ≈ 3,5 mm" },
      { label: "Laçage", value: "Système de laçage rapide élastique, avec œillet de réglage supplémentaire" },
      { label: "Usage", value: "Marche urbaine, voyage, station debout prolongée, port quotidien. Ce n’est pas une chaussure de running." },
      { label: "Largeurs disponibles", value: "Une seule largeur (standard)" },
      { label: "Fabrication", value: "Viêt Nam" },
      { label: "Prix public conseillé On", value: "170 € TTC" },
    ],
  }),
  model({
    slug: "cloudtilt-remix",
    name: "On Cloudtilt Remix",
    brand: "on",
    subcategory: "lifestyle",
    genres: ["mixte"],
    price: 4999,
    shortDescription: "Le confort de la Cloudtilt, avec un look « rayons X ». Construction entièrement thermocollée, superpositions semi-transparentes et logo découpé.",
    curatorNote: "La construction thermocollée sans couture est ce qui la distingue : pas de surpiqûre, des superpositions semi-transparentes, un logo découpé dans la matière. Sortie en février 2026, c'est le modèle le plus récent du catalogue.",
    material: "Synthétique",
    details: [
      { title: "Description complète", content: "Sortie en février 2026, la Cloudtilt Remix reprend la semelle et l'amorti CloudTec Phase® de la Cloudtilt, mais réinvente entièrement le haut de la chaussure. Aucune couture : chaque élément est fusionné thermiquement à la tige, ce qui crée des superpositions semi-transparentes laissant deviner les couches inférieures — un effet « rayons X » assumé, souligné par un logo On découpé à même la matière.\n\nDifférence fonctionnelle importante par rapport à la Cloudtilt standard : le Remix abandonne le laçage rapide élastique au profit d'un laçage classique. On y gagne en précision de serrage et en maintien, on y perd le côté « on l'enfile d'un geste ». La matière déclarée par On est un TPEE, un élastomère thermoplastique polyester.\n\nPositionnement identique : marche urbaine, port quotidien, journées actives. C'est la version la plus structurée et la plus visuellement marquée des deux." },
    ],
    colors: [
      { name: "Gris foncé / noir", hex: "#5A5A5F", images: ["/produits/cloudtilt-remix/1.jpg"] },
      { name: "Blanc intégral", hex: "#F1F0EE", images: ["/produits/cloudtilt-remix/2.jpg"] },
      { name: "Gris / orange corail", hex: "#909093", images: ["/produits/cloudtilt-remix/3.jpg"] },
      { name: "Blanc / bleu roi", hex: "#F1F0EE", images: ["/produits/cloudtilt-remix/4.jpg"] },
      { name: "Lilas / violet clair", hex: "#BFA8D4", images: ["/produits/cloudtilt-remix/5.jpg"] },
      { name: "Rose / corail", hex: "#E79BB0", images: ["/produits/cloudtilt-remix/6.jpg"] },
      { name: "Lilas pâle / violet", hex: "#BFA8D4", images: ["/produits/cloudtilt-remix/7.jpg"] },
      { name: "Noir / blanc / gris", hex: "#1C1C1E", images: ["/produits/cloudtilt-remix/8.jpg"] },
    ],
    sizeAdvice: "Taille normalement (mention officielle On, fiches homme et femme). Une seule largeur proposée. Le moule étant partagé avec la Cloudtilt standard, on peut s'attendre à un avant-pied de largeur comparable (≈ 71,6 mm), sans que cela ait été mesuré sur le Remix.",
    isNew: true,
    curatedRank: 13,
    reviews: [],
    pairsWith: ["cloudmonster-3", "cloudsurfer-max", "cloudtilt"],
    tone: "chalk",
    features: [
      "Amorti CloudTec Phase® à Clouds inclinés",
      "Construction thermocollée sans couture (no-sew)",
      "Superpositions semi-transparentes, effet « rayons X »",
      "Logo On découpé dans la matière",
      "Laçage classique (contrairement à la Cloudtilt standard)",
      "Matière déclarée : TPEE",
    ],
    specifications: [
      { label: "Catégorie", value: "Lifestyle / marche urbaine — gamme Active Life On" },
      { label: "Année de sortie", value: "2026 (février 2026)" },
      { label: "Poids", value: "Non publié par On. Un revendeur annonce ≈ 283 g (10 oz), pointure de référence non précisée." },
      { label: "Drop", value: "Non communiqué par la marque" },
      { label: "Hauteurs de semelle", value: "Non communiqué par la marque" },
      { label: "Tige", value: "Construction thermocollée sans couture, superpositions semi-transparentes, logo découpé. Matière déclarée : TPEE (élastomère thermoplastique polyester)." },
      { label: "Semelle intermédiaire", value: "CloudTec Phase® + mousse Helion™" },
      { label: "Semelle extérieure", value: "Non communiqué par la marque" },
      { label: "Semelle de propreté", value: "Non communiqué par la marque" },
      { label: "Laçage", value: "Laçage classique à lacets" },
      { label: "Usage", value: "Marche urbaine, port quotidien, journées actives. Ce n’est pas une chaussure de running." },
      { label: "Largeurs disponibles", value: "Une seule largeur (standard)" },
      { label: "Fabrication", value: "Viêt Nam" },
      { label: "Prix public conseillé On", value: "170 € TTC" },
    ],
  }),
  model({
    slug: "air-max-plus",
    name: "Nike Air Max Plus",
    brand: "nike",
    subcategory: "lifestyle",
    genres: ["mixte"],
    price: 4999,
    shortDescription: "La TN. Cage TPU inspirée d'une queue de baleine, dégradé de coucher de soleil et double unité Air visible : depuis 1998, la silhouette la plus identifiable de Nike.",
    curatorNote: "La Tuned Air insère des hémisphères de polymère dans l'unité Air pour régler la pression zone par zone : c'est ce qui explique la sensation ferme de la TN, moins moelleuse que sa hauteur ne le laisse croire. Environ 398 g — à savoir avant une journée entière debout.",
    material: "Mesh & synthétique",
    details: [
      { title: "Description complète", content: "Dessinée par Sean McDowell et sortie en octobre 1998, l'Air Max Plus est née d'un coucher de soleil en Floride : le dégradé de la tige reprend le ciel qui vire au bleu nuit, les nervures TPU les palmiers pliés par le vent, et la grande arche latérale la queue d'une baleine. C'était alors la chaussure la plus chère de chez Foot Locker, à 125 dollars.\n\nSous le pied, la technologie Tuned Air : plutôt que d'augmenter le volume d'air, Nike y insère des hémisphères de polymère prémoulés qui permettent de régler la pression zone par zone — souple sous le talon à l'impact, plus ferme là où il faut du maintien. Les bulles sont visibles à l'avant-pied comme au talon.\n\nEn France, et particulièrement à Marseille et en région parisienne, la TN a dépassé depuis longtemps le statut de sneaker pour devenir un marqueur culturel. Elle n'a jamais été arrêtée depuis 1998." },
    ],
    colors: [
      { name: "Blanc intégral", hex: "#F1F0EE", images: ["/produits/air-max-plus/1.jpg"] },
      { name: "Noir / bleu dégradé", hex: "#1C1C1E", images: ["/produits/air-max-plus/2.jpg"] },
      { name: "Bleu roi / marine dégradé", hex: "#22499E", images: ["/produits/air-max-plus/3.jpg"] },
      { name: "Noir → blanc dégradé, bulle bleue", hex: "#1C1C1E", images: ["/produits/air-max-plus/4.jpg"] },
      { name: "Noir / argent métallisé", hex: "#1C1C1E", images: ["/produits/air-max-plus/5.jpg"] },
      { name: "Dégradé vert menthe → orange", hex: "#93D3B8", images: ["/produits/air-max-plus/6.jpg"] },
      { name: "Noir / rouge dégradé", hex: "#1C1C1E", images: ["/produits/air-max-plus/7.jpg"] },
      { name: "Gris / orange dégradé", hex: "#909093", images: ["/produits/air-max-plus/8.jpg"] },
      { name: "Noir intégral", hex: "#1C1C1E", images: ["/produits/air-max-plus/9.jpg"] },
    ],
    sizeAdvice: "Nike indique officiellement que le modèle chausse petit et recommande de prendre une demi-pointure au-dessus. Les retours utilisateurs confirment. L'avant-pied est large (70,9 mm) mais le volume vertical est faible (25,4 mm) : le serrage se fait sentir sur le dessus du pied, et les matériaux demandent un temps de rodage. À déconseiller aux coups de pied très hauts.",
    isNew: false,
    curatedRank: 6,
    reviews: [],
    pairsWith: ["air-max-90", "air-force-1-07", "p-6000"],
    tone: "graphite",
    features: [
      "Technologie Tuned Air : pression d'air réglée zone par zone",
      "Double unité Air visible, talon et avant-pied",
      "Cage TPU « queue de baleine » et nervures « palmiers »",
      "Bout renforcé en TPU brillant",
      "Dégradés sublimés emblématiques du modèle",
      "Gomme extérieure très dure (92 HC) : usure lente",
    ],
    specifications: [
      { label: "Catégorie", value: "Lifestyle, à l’origine chaussure de running" },
      { label: "Création", value: "1998 — designer Sean McDowell. Technologie Tuned Air développée par Joe Skaja en 1991." },
      { label: "Amorti", value: "Tuned Air + Max Air. Unités Air pressurisées contenant des hémisphères de polymère prémoulés, permettant de moduler la pression selon les zones." },
      { label: "Tige", value: "Mesh résistant et respirant, détails en cuir synthétique, cage TPU structurelle" },
      { label: "Semelle intermédiaire", value: "Mousse" },
      { label: "Semelle extérieure", value: "Caoutchouc" },
      { label: "Doublure", value: "Non communiqué par la marque" },
      { label: "Poids", value: "≈ 398 g (mesure en laboratoire indépendant, pointure US 9). Nike ne publie pas cette donnée." },
      { label: "Drop", value: "≈ 11,7 mm (laboratoire). Stack : talon 39,8 mm / avant-pied 28,1 mm." },
      { label: "Signature visuelle", value: "Arche TPU « whale tail », nervures « TPU fingers », bout TPU, dégradé sublimé, logo hexagonal Tn Air au talon" },
      { label: "Usage", value: "Lifestyle et port quotidien" },
      { label: "Prix public conseillé Nike", value: "189,99 € TTC (nike.com/fr, relevé le 21 août 2026)" },
    ],
  }),
  model({
    slug: "air-max-90",
    name: "Nike Air Max 90",
    brand: "nike",
    subcategory: "lifestyle",
    genres: ["mixte"],
    price: 4999,
    shortDescription: "1990, Tinker Hatfield, et une fenêtre d'air cerclée d'Infrared. La sneaker qui a rendu l'amorti visible.",
    curatorNote: "Unité Max Air visible au talon, semelle Waffle, dessin de Tinker Hatfield en 1990 sous le nom d'Air Max III. Une silhouette qui n'a jamais eu besoin d'être remise au goût du jour.",
    material: "Cuir & mesh",
    details: [
      { title: "Description complète", content: "Lancée en 1990 sous le nom d'Air Max III, la 90 a été rebaptisée d'après son année de sortie lors de sa réédition, au tournant des années 2000. Tinker Hatfield y agrandit l'unité Max Air et l'encadre d'un mudguard en plastique nervuré teinté de rouge vif — un rouge que le public rebaptisera « Infrared ». L'idée était simple : forcer le regard vers la bulle d'air.\n\nLe reste de la construction est du pur héritage running Nike : semelle gaufrée Waffle, empiècements cousus, détails TPU, col rembourré, motifs réfléchissants. La tige combine textile et empiècements cuir ou cuir synthétique selon les coloris.\n\nAu-delà du running, la 90 est devenue une pièce centrale de la culture grime londonienne au début des années 2000, portée notamment par Dizzee Rascal et Wiley. Elle a depuis été déclinée par HUF, sacai, Off-White, KAWS, atmos et Patta." },
    ],
    colors: [
      { name: "Gris clair / bleu marine", hex: "#C3C3C1", images: ["/produits/air-max-90/1.jpg"] },
      { name: "Noir intégral (cuir)", hex: "#1C1C1E", images: ["/produits/air-max-90/2.jpg"] },
      { name: "Blanc intégral", hex: "#F1F0EE", images: ["/produits/air-max-90/3.jpg"] },
    ],
    sizeAdvice: "Taille normalement — c'est le consensus des retours utilisateurs, Nike n'affichant pas de note de taille sur ce modèle. Largeur standard, pas d'option de largeur alternative. Pied large : prendre une demi-pointure au-dessus.",
    isNew: false,
    curatedRank: 2,
    reviews: [],
    pairsWith: ["air-max-plus", "air-force-1-07", "p-6000"],
    tone: "chalk",
    features: [
      "Unité Max Air visible au talon",
      "Semelle gaufrée Waffle, héritage running Nike",
      "Mudguard TPU nervuré autour de la fenêtre d'air",
      "Empiècements cuir et cuir synthétique cousus",
      "Motifs réfléchissants et col rembourré",
      "Excellente respirabilité (notée 5/5 en test)",
    ],
    specifications: [
      { label: "Catégorie", value: "Lifestyle, à l’origine chaussure de running" },
      { label: "Création", value: "1990 — designer Tinker Hatfield. Nom d’origine : Air Max III." },
      { label: "Amorti", value: "Max Air. Unité Air visible au talon, de volume supérieur à celle de l’Air Max 1." },
      { label: "Tige", value: "Textile avec empiècements en cuir et cuir synthétique cousus. La composition exacte varie selon les coloris." },
      { label: "Semelle intermédiaire", value: "Mousse" },
      { label: "Semelle extérieure", value: "Caoutchouc à motif gaufré (Waffle)" },
      { label: "Doublure", value: "Non communiqué par la marque" },
      { label: "Poids", value: "≈ 380 g (mesure en laboratoire indépendant). Nike ne publie pas cette donnée." },
      { label: "Drop", value: "≈ 14,2 mm (laboratoire). Stack : talon 36,4 mm / avant-pied 22,2 mm." },
      { label: "Signature visuelle", value: "Fenêtre Air visible cerclée d’Infrared, mudguard nervuré, heel tab, œillets larges" },
      { label: "Usage", value: "Lifestyle et port quotidien" },
      { label: "Prix public conseillé Nike", value: "149,99 € homme / 159,99 € femme (nike.com/fr, relevé le 21 août 2026)" },
    ],
  }),
  model({
    slug: "air-force-1-07",
    name: "Nike Air Force 1 '07",
    brand: "nike",
    subcategory: "lifestyle",
    genres: ["mixte"],
    price: 4999,
    shortDescription: "La meilleure vente de tous les temps de Nike. Cuir lisse, unité Air encapsulée et cercles de pivot hérités du basket de 1982.",
    curatorNote: "Cuir véritable, unité Air encapsulée et invisible, environ 465 g : c'est la plus lourde et la plus rigide des silhouettes du catalogue. Le temps de rodage est long — ceux qui la connaissent le savent, ceux qui la découvrent doivent le savoir avant de commander.",
    material: "Cuir",
    details: [
      { title: "Description complète", content: "Dessinée par Bruce Kilgore et sortie fin octobre 1982, l'Air Force 1 est la première chaussure de basket Nike équipée d'une unité Air. La marque annonçait alors 30 % d'absorption des chocs en plus qu'une chaussure standard. La forme du talon est directement empruntée à une chaussure de randonnée Nike, l'Approach, dont le talon abaissé soulageait le tendon d'Achille.\n\nLe suffixe '07 désigne la version lancée en 2007 pour les 25 ans du modèle : bijou de lacet métallique plus anguleux, surpiqûres affinées, cuir de meilleure qualité, amorti revu — les proportions d'origine étant conservées.\n\nArrêtée en 1984, relancée en 1986 par des détaillants de la côte Est américaine, elle est considérée comme la première rétro-sortie de l'histoire de la sneaker. Plus de 2 000 déclinaisons ont été recensées depuis." },
    ],
    colors: [
      { name: "Blanc / Swoosh noir", hex: "#F1F0EE", images: ["/produits/air-force-1-07/1.jpg"] },
      { name: "Noir intégral", hex: "#1C1C1E", images: ["/produits/air-force-1-07/2.jpg"] },
      { name: "Blanc intégral", hex: "#F1F0EE", images: ["/produits/air-force-1-07/3.jpg"] },
    ],
    sizeAdvice: "Nike indique officiellement que le modèle chausse grand et recommande de prendre une demi-pointure en dessous. Les retours utilisateurs, très nombreux, penchent en revanche majoritairement pour la pointure habituelle. Le plus prudent en fiche produit : reprendre la consigne Nike tout en signalant cette divergence. La largeur est généreuse et l'avant-pied arrondi, ce qui convient bien aux pieds larges.",
    isNew: false,
    curatedRank: 1,
    reviews: [],
    pairsWith: ["air-max-plus", "air-max-90", "p-6000"],
    tone: "chalk",
    features: [
      "Tige en cuir véritable, surpiqûres apparentes",
      "Unité Nike Air encapsulée quasi pleine longueur",
      "Construction cupsole rigide et durable",
      "Cercles de pivot sur la semelle, héritage basket",
      "Perforations d'aération sur la pointe",
      "Bijou de lacet (dubrae) métallique",
    ],
    specifications: [
      { label: "Catégorie", value: "Lifestyle, à l’origine chaussure de basketball" },
      { label: "Création", value: "1982 — designer Bruce Kilgore. La déclinaison « ’07 » date de 2007 (25e anniversaire)." },
      { label: "Amorti", value: "Unité Nike Air encapsulée, non visible, conçue à l’origine pour le basket de compétition" },
      { label: "Tige", value: "Cuir véritable lisse avec renforts cousus, perforations sur la pointe" },
      { label: "Semelle intermédiaire", value: "Mousse" },
      { label: "Semelle extérieure", value: "Caoutchouc, avec cercles de pivot hérités du design basket" },
      { label: "Doublure", value: "Non communiqué par la marque" },
      { label: "Poids", value: "≈ 465 g (mesure en laboratoire indépendant) — la plus lourde des silhouettes Nike emblématiques testées" },
      { label: "Drop", value: "≈ 14,5 mm (laboratoire). Stack : talon 31,7 mm / avant-pied 17,2 mm." },
      { label: "Signature visuelle", value: "Cupsole, bijou de lacet métallique, heel tab logotypé, col bas rembourré" },
      { label: "Usage", value: "Lifestyle et port quotidien. Chaussure lourde et rigide : le temps de rodage est long." },
      { label: "Prix public conseillé Nike", value: "119,99 € TTC (nike.com/fr, relevé le 21 août 2026)" },
    ],
  }),
  model({
    slug: "p-6000",
    name: "Nike P-6000",
    brand: "nike",
    subcategory: "lifestyle",
    genres: ["mixte"],
    price: 4999,
    shortDescription: "L'esprit Y2K de Nike. Tissu métallisé, treillis de renforts chromés et détails réfléchissants, sur une base d'Air Pegasus 2006.",
    curatorNote: "Une confusion fréquente mérite d'être levée : la P-6000 n'a pas d'unité Air, contrairement aux trois autres Nike du catalogue. C'est une silhouette Y2K dérivée de l'Air Pegasus 2006, que Nike présente comme conçue pour la marche.",
    material: "Synthétique",
    details: [
      { title: "Description complète", content: "Sortie en 2019, la P-6000 est une relecture assumée de la Nike Air Pegasus 2006 — le « P » du nom renvoie d'ailleurs à Pegasus. Nike y greffe un vocabulaire visuel années 2000 : tissu métallisé respirant, renforts horizontaux et verticaux en cuir synthétique chromé formant un treillis sur toute la tige, fenêtres ajourées sur la pointe et le talon, Swoosh moulé et détails réfléchissants.\n\nC'est la plus légère des quatre silhouettes Nike du catalogue : environ 292 g, soit près de 40 % de moins que la moyenne de sa catégorie. Point important à dire clairement en fiche : elle ne contient aucune unité Air. Sa semelle intermédiaire est en mousse simple, sans technologie Nike brevetée.\n\nNike la positionne explicitement pour la marche. C'est une chaussure de style avant tout, portée par la vague « dad shoe » et le retour du normcore." },
    ],
    colors: [
      { name: "Blanc / gris / Swoosh volt", hex: "#F1F0EE", images: ["/produits/p-6000/1.jpg"] },
      { name: "Gris / argent / bleu roi", hex: "#909093", images: ["/produits/p-6000/2.jpg"] },
      { name: "Noir / argent métallisé", hex: "#1C1C1E", images: ["/produits/p-6000/3.jpg"] },
      { name: "Blanc / argent / bleu pâle", hex: "#F1F0EE", images: ["/produits/p-6000/4.jpg"] },
      { name: "Gris / blanc / bleu pétrole", hex: "#909093", images: ["/produits/p-6000/5.jpg"] },
      { name: "Crème / dégradé orange-jaune-vert", hex: "#EDE6D7", images: ["/produits/p-6000/6.jpg"] },
      { name: "Vert sauge / gris pâle", hex: "#9AA88C", images: ["/produits/p-6000/7.jpg"] },
      { name: "Noir intégral", hex: "#1C1C1E", images: ["/produits/p-6000/8.jpg"] },
      { name: "Blanc / gris / noir", hex: "#F1F0EE", images: ["/produits/p-6000/9.jpg"] },
      { name: "Noir / anthracite", hex: "#1C1C1E", images: ["/produits/p-6000/10.jpg"] },
      { name: "Gris / argent / blanc", hex: "#909093", images: ["/produits/p-6000/11.jpg"] },
    ],
    sizeAdvice: "Taille normalement. Largeur standard (avant-pied mesuré à 93,9 mm), forme arrondie et tolérante sur de longues durées de port. C'est la plus confortable à enfiler des quatre silhouettes Nike de ce catalogue.",
    isNew: false,
    curatedRank: 7,
    reviews: [],
    pairsWith: ["air-max-plus", "air-max-90", "air-force-1-07"],
    tone: "graphite",
    features: [
      "La plus légère de la sélection Nike : ≈ 292 g",
      "Tissu métallisé + renforts chromés en treillis",
      "Fenêtres ajourées sur la pointe et le talon",
      "Détails réfléchissants",
      "Semelle gaufrée héritée de l'Air Pegasus 2006",
      "Excellente respirabilité (notée 5/5 en test)",
    ],
    specifications: [
      { label: "Catégorie", value: "Lifestyle / marche — silhouette Y2K" },
      { label: "Création", value: "2019. Basée sur la Nike Air Pegasus 2006. Designer non documenté publiquement." },
      { label: "Amorti", value: "Semelle intermédiaire en mousse simple. Aucune unité Air, aucune technologie Nike brevetée." },
      { label: "Tige", value: "Tissu métallisé respirant, renforts horizontaux et verticaux en cuir synthétique chromé" },
      { label: "Semelle intermédiaire", value: "Mousse, rainures ondulées héritées des Pegasus" },
      { label: "Semelle extérieure", value: "Caoutchouc pleine longueur, pads gaufrés" },
      { label: "Doublure", value: "Non communiqué par la marque" },
      { label: "Poids", value: "≈ 292 g (mesure en laboratoire indépendant)" },
      { label: "Drop", value: "≈ 9,0 mm (laboratoire). Stack : talon 29,7 mm / avant-pied 20,7 mm." },
      { label: "Signature visuelle", value: "Treillis de renforts, fenêtres ajourées, Swoosh moulé, détails réfléchissants" },
      { label: "Usage", value: "Lifestyle et marche. Nike la présente comme « conçue pour la marche »." },
      { label: "Prix public conseillé Nike", value: "119,99 € TTC (nike.com/fr, relevé le 21 août 2026)" },
    ],
  }),
  model({
    slug: "progrid-ride-1",
    name: "Saucony ProGrid Ride 1",
    brand: "saucony",
    subcategory: "lifestyle",
    genres: ["mixte"],
    price: 5999,
    shortDescription: "De retour après presque 18 ans. Mesh hexagonal, cage médio-pied ajourée et amorti ProGrid au talon : la Ride 1 de 2008, telle quelle.",
    curatorNote: "Une réédition d'archive : modèle de 2008, revenu en 2026 dans la gamme Originals. Le mesh hexagonal à mailles ouvertes et l'arceau médio-pied ajouré en sont les marqueurs visuels immédiats.",
    material: "Mesh & synthétique",
    details: [
      { title: "Description complète", content: "Sortie en 2008 comme daily trainer polyvalent à amorti neutre, la ProGrid Ride 1 revient en 2026 dans la gamme Originals de Saucony — une réédition d'archive, présentée à la Paris Fashion Week avant une sortie élargie le 15 juillet 2026.\n\nSa signature visuelle tient en trois éléments : un mesh hexagonal à mailles très ouvertes qui laisse passer l'air, une cage-arceau ajourée qui enveloppe le médio-pied et assure la rigidité en torsion, et des overlays géométriques métallisés qui accrochent la lumière. Au talon, l'insert ProGrid absorbe l'impact — une technologie que Saucony décrit comme « plus réactive que l'EVA, pour un amorti considérable dans un ensemble léger ».\n\nAujourd'hui, c'est une chaussure lifestyle. Son ADN reste celui d'un modèle neutre : pas de correction de pronation, pas de dispositif de stabilité." },
    ],
    colors: [
      { name: "Blanc / rouge / argent", hex: "#F1F0EE", images: ["/produits/progrid-ride-1/1.jpg"] },
      { name: "Noir / gris", hex: "#1C1C1E", images: ["/produits/progrid-ride-1/2.jpg"] },
      { name: "Blanc / argent", hex: "#F1F0EE", images: ["/produits/progrid-ride-1/3.jpg"] },
    ],
    sizeAdvice: "Saucony affiche sur sa fiche produit une recommandation générale : sur les modèles performance, prendre jusqu'à une pointure au-dessus de sa pointure habituelle. Il n'existe pas de retour utilisateur consolidé spécifique à cette réédition. Prudence à afficher en fiche : conseiller d'essayer, ou de prendre une demi-pointure au-dessus en cas de doute. Une seule largeur proposée.",
    isNew: false,
    curatedRank: 12,
    reviews: [],
    pairsWith: ["progrid-omni-9"],
    tone: "chalk",
    features: [
      "Amorti ProGrid au talon, plus réactif que l'EVA",
      "Mesh hexagonal à mailles ouvertes, très respirant",
      "Cage-arceau médio-pied ajourée, rigidité en torsion",
      "Overlays géométriques métallisés",
      "Semelle extérieure en caoutchouc cranté",
      "Réédition fidèle du modèle de 2008",
    ],
    specifications: [
      { label: "Catégorie", value: "Lifestyle — gamme Originals de Saucony (réédition d’archive)" },
      { label: "Modèle d’origine", value: "2008 — daily trainer running à amorti neutre" },
      { label: "Réédition", value: "2026 — sortie limitée le 26 juin, sortie élargie le 15 juillet" },
      { label: "Amorti", value: "ProGrid au talon : insert conçu pour absorber l’impact, décrit par Saucony comme plus réactif que l’EVA" },
      { label: "Tige", value: "Mesh hexagonal à mailles ouvertes, overlays synthétiques métallisés, cage-arceau médio-pied ajourée, doublure textile" },
      { label: "Semelle intermédiaire", value: "Mousse EVA + insert ProGrid au talon" },
      { label: "Semelle extérieure", value: "Caoutchouc cranté" },
      { label: "Semelle de propreté", value: "Semelle moulée" },
      { label: "Poids", value: "Non communiqué par la marque" },
      { label: "Drop", value: "Non communiqué par la marque" },
      { label: "Usage", value: "Lifestyle. À l’origine : running route, foulée neutre. Pas de correction de pronation." },
      { label: "Largeurs disponibles", value: "Largeur standard (Medium) uniquement" },
      { label: "Prix public conseillé Saucony", value: "150 € TTC (saucony.com FR)" },
    ],
  }),
  model({
    slug: "progrid-omni-9",
    name: "Saucony ProGrid Omni 9",
    brand: "saucony",
    subcategory: "lifestyle",
    genres: ["mixte"],
    price: 5999,
    shortDescription: "La dad shoe Y2K par excellence. Mesh, daim et cuir superposés, cage TPU médio-pied et argenté omniprésent : lancée en 2010, revenue en 2023 — et jamais repartie.",
    curatorNote: "Treize coloris : c'est le modèle le plus décliné du catalogue. Les mentions de stabilité et de contrôle de pronation appartiennent à son passé running de 2010 — nous ne la vendons pas comme une chaussure correctrice, et la fiche technique le précise.",
    material: "Mesh & daim",
    details: [
      { title: "Description complète", content: "« Lancée en 2010, la ProGrid Omni 9 n'était pas seulement en avance sur son temps : elle l'a défini. » C'est ainsi que Saucony présente le modèle. À l'origine, c'était une chaussure de running de stabilité, construite pour contrôler la pronation sur de longues distances. Aujourd'hui, c'est l'une des silhouettes les plus recherchées de la vague rétro-running.\n\nLa construction empile les couches : mesh ouvert, empiècements daim et cuir, cage TPU au médio-pied pour la rigidité en torsion, semelle intermédiaire EVA pleine longueur combinant les technologies ProGrid, GRID et SRC (Super Rebound Compound), et semelle extérieure caoutchouc à pads d'accroche. Le tout dans des tonalités argentées typiquement Y2K.\n\nLe modèle a été décliné avec Jae Tips, Callen Schaub, Starcow, Footpatrol et Sneaker Politics, en plus des séries maison Crystal Cave, Armor et Glowaconstrictor." },
    ],
    colors: [
      { name: "Blanc / turquoise / corail / volt", hex: "#F1F0EE", images: ["/produits/progrid-omni-9/1.jpg"] },
      { name: "Blanc / gris / taupe", hex: "#F1F0EE", images: ["/produits/progrid-omni-9/2.jpg"] },
      { name: "Blanc / bordeaux / argent", hex: "#F1F0EE", images: ["/produits/progrid-omni-9/3.jpg"] },
      { name: "Menthe / orange / bleu / volt", hex: "#93D3B8", images: ["/produits/progrid-omni-9/4.jpg"] },
      { name: "Blanc / argent / gris", hex: "#F1F0EE", images: ["/produits/progrid-omni-9/5.jpg"] },
      { name: "Rouge / rose / argent", hex: "#C0392B", images: ["/produits/progrid-omni-9/6.jpg"] },
      { name: "Blanc / gris / corail", hex: "#F1F0EE", images: ["/produits/progrid-omni-9/7.jpg"] },
      { name: "Blanc / turquoise / argent", hex: "#F1F0EE", images: ["/produits/progrid-omni-9/8.jpg"] },
      { name: "Blanc / argent / bleu ciel", hex: "#F1F0EE", images: ["/produits/progrid-omni-9/9.jpg"] },
      { name: "Blanc / argent / rouge", hex: "#F1F0EE", images: ["/produits/progrid-omni-9/10.jpg"] },
      { name: "Blanc / noir / argent", hex: "#F1F0EE", images: ["/produits/progrid-omni-9/11.jpg"] },
      { name: "Noir / gris / argent", hex: "#1C1C1E", images: ["/produits/progrid-omni-9/12.jpg"] },
      { name: "Blanc / corail / bleu / volt", hex: "#F1F0EE", images: ["/produits/progrid-omni-9/13.jpg"] },
    ],
    sizeAdvice: "Chausse petit : les revendeurs agréés recommandent une demi-pointure au-dessus. Modèle unisexe, dont les pointures affichées sont des pointures homme — une femme doit descendre d'environ 1,5 pointure US par rapport à sa pointure running habituelle. Attention également : l'épaisseur du rembourrage varie selon les coloris, ce qui modifie légèrement le ressenti. Une seule largeur proposée.",
    isNew: false,
    curatedRank: 9,
    reviews: [],
    pairsWith: ["progrid-ride-1"],
    tone: "signal",
    features: [
      "Amorti ProGrid + GRID + SRC (Super Rebound Compound)",
      "Cage TPU médio-pied : rigidité en torsion",
      "Tige mesh ouvert avec empiècements daim et cuir",
      "Semelle intermédiaire EVA pleine longueur",
      "Silhouette « dad shoe » Y2K très demandée",
      "Nombreuses collaborations depuis 2023",
    ],
    specifications: [
      { label: "Catégorie", value: "Lifestyle — gamme Originals de Saucony (réédition d’archive)" },
      { label: "Modèle d’origine", value: "2010 — chaussure de running de stabilité, contrôle de la pronation" },
      { label: "Réédition", value: "2023 (première salve médiatisée : série Crystal Cave, octobre 2023)" },
      { label: "Amorti", value: "ProGrid (impact au talon) + GRID (amorti stable au talon) + SRC, Super Rebound Compound (absorption au crash pad)" },
      { label: "Tige", value: "Mesh ouvert, empiècements daim et cuir, cage TPU au médio-pied" },
      { label: "Semelle intermédiaire", value: "EVA pleine longueur + ProGrid + SRC" },
      { label: "Semelle extérieure", value: "Caoutchouc, pads d’accroche multiples" },
      { label: "Semelle de propreté", value: "Non communiqué par la marque" },
      { label: "Poids", value: "Non communiqué par la marque" },
      { label: "Drop", value: "Non communiqué par la marque" },
      { label: "Usage", value: "Lifestyle. À l’origine : running de stabilité pour pronateurs légers à modérés — mention sans valeur prescriptive en usage lifestyle." },
      { label: "Largeurs disponibles", value: "Largeur standard (Regular / D) uniquement" },
      { label: "Prix public conseillé Saucony", value: "160 € TTC (saucony.com FR)" },
    ],
  }),
  model({
    slug: "gel-kayano-14",
    name: "ASICS GEL-KAYANO 14",
    brand: "asics",
    subcategory: "sportstyle",
    genres: ["mixte"],
    price: 5999,
    shortDescription: "Sneaker de l'année 2023 selon GQ. Tige cuir et mesh superposés, GEL™ visible au talon, semelle d'origine de 2008 : la rétro-runner qui a lancé la vague Y2K.",
    curatorNote: "GEL au talon, Trusstic System sous le médio-pied, superposition cuir-mesh de 2008. À ne pas confondre avec la GEL-KAYANO 31/32, qui est la chaussure de running actuelle d'ASICS : celle-ci est une réédition SportStyle.",
    material: "Cuir & mesh",
    details: [
      { title: "Description complète", content: "Sortie en 2008 et dessinée par Hidenori Yamashita autour d'un concept baptisé « Flash », la GEL-KAYANO 14 est le premier modèle de la lignée conçu par quelqu'un d'autre que Toshikazu Kayano. Elle est rééditée en décembre 2020 dans la gamme SportStyle, dans le sillage du travail de Kiko Kostadinov pour la marque.\n\nASICS a conservé le moule de semelle de 2008 et sa construction cuir-mesh superposée. On y retrouve l'insert GEL™ au talon — un silicone spécifique conçu pour l'absorption des chocs — et le Trusstic System™, une pièce moulée sous le médio-pied qui réduit le poids de la semelle tout en contrôlant la torsion. La semelle de propreté utilise un procédé de teinture en solution qui réduit d'environ 33 % la consommation d'eau et de 45 % les émissions de carbone.\n\nÉlue sneaker de l'année 2023 par GQ, elle a été déclinée avec JJJJound, Kiko Kostadinov, P.Andrade, Aritzia et, en mars 2026, Thom Browne — première collaboration sneaker de la maison." },
    ],
    colors: [
      { name: "Noir / argent", hex: "#1C1C1E", images: ["/produits/gel-kayano-14/1.jpg"] },
      { name: "Noir / crème / gris", hex: "#1C1C1E", images: ["/produits/gel-kayano-14/2.jpg"] },
      { name: "Blanc / bleu ciel / argent", hex: "#F1F0EE", images: ["/produits/gel-kayano-14/3.jpg"] },
      { name: "Blanc / argent / crème", hex: "#F1F0EE", images: ["/produits/gel-kayano-14/4.jpg"] },
    ],
    sizeAdvice: "Taille normalement, confirmé par les retours utilisateurs. L'avant-pied est plus large que la moyenne du marché (100,3 mm à la partie la plus large), ce qui en fait un bon choix pour les pieds larges. Largeur catalogue standard.",
    isNew: false,
    curatedRank: 5,
    reviews: [],
    pairsWith: ["gel-kayano-20"],
    tone: "graphite",
    features: [
      "Insert GEL™ visible au talon, amorti d'origine 2008",
      "Trusstic System™ : contrôle de la torsion, semelle allégée",
      "Tige cuir et mesh superposés, overlays métallisés",
      "Semelle de propreté Solution Dye : −33 % d'eau, −45 % de CO₂",
      "Accents réfléchissants et col matelassé",
      "Avant-pied plus large que la moyenne",
    ],
    specifications: [
      { label: "Catégorie", value: "Lifestyle — gamme SportStyle d’ASICS" },
      { label: "Modèle d’origine", value: "2008 — designer Hidenori Yamashita, concept « Flash »" },
      { label: "Réédition", value: "Décembre 2020" },
      { label: "Amorti", value: "Technologie GEL™ au talon : silicone spécifique conçu pour une absorption optimale des chocs. Moule de semelle intermédiaire d’origine 2008 conservé." },
      { label: "Maintien", value: "Trusstic System™ — pièce moulée sous le médio-pied qui allège la semelle tout en contrôlant la torsion" },
      { label: "Tige", value: "Cuir et mesh superposés, overlays synthétiques ou cuir métallisé selon les coloris, accents réfléchissants, col matelassé" },
      { label: "Semelle intermédiaire", value: "EVA + insert GEL™ au talon (densité mesurée : 60,9 Asker C, mousse ferme)" },
      { label: "Semelle extérieure", value: "Caoutchouc, épaisseur ≈ 4,7 mm" },
      { label: "Semelle de propreté", value: "Procédé Solution Dye : environ −33 % de consommation d’eau et −45 % d’émissions de carbone" },
      { label: "Poids", value: "≈ 352 g (mesure en laboratoire indépendant). ASICS ne publie pas cette donnée." },
      { label: "Drop", value: "≈ 10,1 mm (laboratoire). Stack : talon 32,7 mm / avant-pied 22,6 mm." },
      { label: "Usage", value: "Lifestyle. Le modèle de 2008 était une chaussure de stabilité — la réédition ne doit pas être vendue comme correctrice." },
      { label: "Prix public conseillé ASICS", value: "170 € TTC (asics.com/fr)" },
    ],
  }),
  model({
    slug: "gel-kayano-20",
    name: "ASICS GEL-KAYANO 20",
    brand: "asics",
    subcategory: "sportstyle",
    genres: ["mixte"],
    price: 5999,
    shortDescription: "Double insert GEL™, avant et arrière. Cage TPU FluidFit™ en croisillons et esthétique architecturale : le modèle anniversaire de 2013, remis au catalogue.",
    curatorNote: "Le croisillon FluidFit™ en TPU posé en zigzag est sa signature visuelle. Elle a du GEL à l'avant-pied ET au talon, là où la KAYANO 14 n'en a qu'au talon — c'est la principale différence de sensation entre les deux.",
    material: "Mesh & synthétique",
    details: [
      { title: "Description complète", content: "Lancée en 2013 pour les vingt ans de la franchise GEL-KAYANO, la 20 est la plus technique de la lignée : deux inserts GEL™, à l'avant-pied et au talon, une semelle intermédiaire FluidRide™ tri-densité associée au système de maintien Dynamic DuoMax™, et un Guidance Trusstic™ System qui guide la transition talon-pointe tout en contrôlant la torsion.\n\nSa signature visuelle, c'est la cage FluidFit™ : une application de TPU en croisillons, posée en zigzag sur des zones ciblées de la tige, qui produit un chaussant « seconde peau ». ASICS revendique ouvertement une inspiration architecturale et automobile pour cette silhouette.\n\nRééditée à partir de 2024 dans la gamme SportStyle, elle a été déclinée avec KENZO, Bodega, UNAFFECTED, HAL STUDIOS et Completedworks." },
    ],
    colors: [
      { name: "Blanc / gris / jaune fluo", hex: "#F1F0EE", images: ["/produits/gel-kayano-20/1.jpg"] },
      { name: "Noir / argent", hex: "#1C1C1E", images: ["/produits/gel-kayano-20/2.jpg"] },
      { name: "Noir / bleu ciel", hex: "#1C1C1E", images: ["/produits/gel-kayano-20/3.jpg"] },
    ],
    sizeAdvice: "Le chaussant est jugé légèrement étroit. Prendre sa pointure habituelle, et une demi-pointure au-dessus en cas de pied large. À noter : le modèle running de 2013 était au contraire réputé volumineux à l'avant — cette caractéristique ne se transpose pas à la réédition.",
    isNew: false,
    curatedRank: 11,
    reviews: [],
    pairsWith: ["gel-kayano-14"],
    tone: "chalk",
    features: [
      "Double insert GEL™ : avant-pied et talon",
      "Cage TPU FluidFit™ en croisillons, chaussant seconde peau",
      "Guidance Trusstic™ System : guidage et contrôle de la torsion",
      "Semelle intermédiaire FluidRide™ tri-densité",
      "Système de maintien Dynamic DuoMax™",
      "Esthétique architecturale, empiècements argentés",
    ],
    specifications: [
      { label: "Catégorie", value: "Lifestyle — gamme SportStyle d’ASICS" },
      { label: "Modèle d’origine", value: "2013 — modèle du 20e anniversaire de la franchise GEL-KAYANO (millésime course 2014)" },
      { label: "Réédition", value: "À partir de 2024" },
      { label: "Amorti", value: "Double système GEL™, à l’avant-pied et à l’arrière-pied, pour l’absorption des chocs" },
      { label: "Maintien", value: "Guidance Trusstic™ System (plaque médio-pied avec ligne de guidage) + Dynamic DuoMax™ (semelle bi-densité de maintien)" },
      { label: "Tige", value: "Mesh respirant, overlays synthétiques et cage TPU FluidFit™ appliquée en croisillons. Cuir sur le bout et les œillets selon les coloris." },
      { label: "Semelle intermédiaire", value: "FluidRide™ — EVA tri-densité + inserts GEL™ + Dynamic DuoMax™" },
      { label: "Semelle extérieure", value: "Caoutchouc" },
      { label: "Semelle de propreté", value: "Non communiqué par la marque" },
      { label: "Poids", value: "Non communiqué par la marque" },
      { label: "Drop", value: "Non communiqué par la marque" },
      { label: "Usage", value: "Lifestyle. Le modèle de 2013 était une chaussure de stabilité — la réédition ne doit pas être vendue comme correctrice." },
      { label: "Prix public conseillé ASICS", value: "170 € TTC (asics.com/fr)" },
    ],
  }),
  model({
    slug: "xt-6",
    name: "Salomon XT-6",
    brand: "salomon",
    subcategory: "sportstyle",
    genres: ["mixte"],
    price: 6999,
    shortDescription: "Née en 2013 sous le nom S/LAB XT-6 pour l'ultra-trail, devenue l'une des sneakers les plus copiées de la décennie. Cinq coloris, dont deux imperméables GORE-TEX.",
    curatorNote: "Née en 2013 pour l'ultra-trail sous le nom S/LAB XT-6, passée en Sportstyle en 2018 sans rien perdre de son équipement : Quicklace, SensiFit, EndoFit, agileCHASSIS. Deux des cinq coloris sont doublés d'une membrane GORE-TEX.",
    material: "Mesh & synthétique",
    details: [
      { title: "Description complète", content: "La XT-6 est l'aboutissement d'une lignée de chaussures de trail conçues pour l'ultra-distance : XT Wings, puis XT-4, XT-5 et enfin XT-6, lancée en 2013 sous le nom S/LAB XT-6. Elle est dessinée par Benjamin Grenet, aujourd'hui responsable du design chaussure chez Salomon, avec un parti pris assumé — rendre la technologie visible plutôt que la masquer.\n\nElle est validée sur le terrain par des athlètes d'ultra-trail, au premier rang desquels François D'Haene, vainqueur de l'UTMB en 2012, 2014 et 2017 et de la Diagonale des Fous en 2016 et 2018. En 2018, Salomon la réédite dans sa gamme Sportstyle : elle quitte le sentier pour la ville et devient l'une des silhouettes les plus reprises de la décennie, portée par des collaborations avec Palace, Kith ou atmos.\n\nL'architecture est identique sur les cinq coloris : châssis agileCHASSIS™ visible sur le flanc, mousse EnergyCell double densité, semelle Mud Contagrip® à crampons profonds, laçage Quicklace™ et maintien SensiFit™ + EndoFit™. Seule la présence de la membrane GORE-TEX varie." },
    ],
    colors: [
      { name: "Noir GORE-TEX", hex: "#1C1C1E", images: ["/produits/xt-6/1.jpg", "/produits/xt-6/2.jpg"] },
      { name: "Blanc / Lunar Rock", hex: "#F1F0EE", images: ["/produits/xt-6/3.jpg", "/produits/xt-6/4.jpg"] },
      { name: "Gris / Gray Flannel", hex: "#909093", images: ["/produits/xt-6/5.jpg", "/produits/xt-6/6.jpg"] },
      { name: "Blanc / argent GORE-TEX", hex: "#F1F0EE", images: ["/produits/xt-6/7.jpg", "/produits/xt-6/8.jpg"] },
      { name: "Noir / rouge / argent", hex: "#1C1C1E", images: ["/produits/xt-6/9.jpg", "/produits/xt-6/10.jpg"] },
    ],
    sizeAdvice: "La XT-6 taille normalement, mais son chaussant est plutôt étroit — c'est un héritage trail assumé, le pied doit être tenu. Pied normal ou fin : pointure habituelle. Pied large : une demi-pointure au-dessus. Sur les deux versions GORE-TEX, la membrane rigidifie la tige : conseiller une demi-pointure au-dessus systématiquement.",
    isNew: false,
    curatedRank: 3,
    reviews: [],
    pairsWith: [],
    tone: "graphite",
    features: [
      "Laçage Quicklace™ : serrage d'un seul geste, lacet rangé dans la languette",
      "Châssis agileCHASSIS™ : stabilité latérale et amorti",
      "Mousse EnergyCell double densité",
      "Semelle Mud Contagrip® à crampons profonds",
      "Maintien SensiFit™ + chausson interne EndoFit™",
      "Deux des cinq coloris sont imperméables (GORE-TEX)",
    ],
    specifications: [
      { label: "Catégorie", value: "Sportstyle — dérivé du trail running" },
      { label: "Création", value: "2013 sous le nom S/LAB XT-6 — designer Benjamin Grenet. Réédition Sportstyle en 2018." },
      { label: "Genre", value: "Unisexe" },
      { label: "Poids", value: "≈ 365 g par chaussure (13 oz), taille de référence" },
      { label: "Drop", value: "10 mm" },
      { label: "Tige", value: "Synthétique / textile, mesh résistant à l’abrasion, renforts thermosoudés, pare-pierres renforcé" },
      { label: "Doublure", value: "Textile respirant (+ membrane GORE-TEX sur les versions GTX)" },
      { label: "Semelle intermédiaire", value: "EnergyCell — mousse EVA double densité + châssis agileCHASSIS™" },
      { label: "Semelle extérieure", value: "Caoutchouc Mud Contagrip® à crampons profonds" },
      { label: "Semelle de propreté", value: "OrthoLite® moulée, amovible" },
      { label: "Laçage", value: "Quicklace™ + poche de rangement du lacet sur la languette" },
      { label: "Maintien", value: "SensiFit™ (enveloppement de la semelle intermédiaire jusqu’au laçage) + EndoFit™ (chausson interne)" },
      { label: "Tailles officielles Salomon", value: "EU 36 à 48, dont demi-pointures et tiers de pointure" },
      { label: "Prix public conseillé Salomon", value: "180 € — version GORE-TEX ≈ 200 €" },
    ],
  }),
];
